### ISSUE TITLE
Suggestion: PWA installable App and Offline Frontend

### ISSUE THREAD

**Issue by wellington1993** [trungk18/angular-spotify#34]
Thinking in educational purpose of the App.
I suggest the PWA architecture implementation.

For make the application works offline(Don't playing song, but accessible). 
This approach can explore concepts with Connection Detection, Service Worker, Local Storage, Cache.

I'm anxious to see that in a Live on Youtube!

Thanks!

**Comment by trungk18** [comment]
That's great suggestion. I am not an expert of PWA but could try, and will also ask for my friend if they can join and teach us about it too.
