### ISSUE TITLE
Suggestion: Move assets from apps folder to libs/shared

### ISSUE THREAD

**Issue by nikosanif** [trungk18/angular-spotify#36]
Awesome work!

I have a suggestion regarding the structure since you use Nx Workspace.
You could move the entire `apps/angular-spotify/src/assets` folder to  a more generic library (e.g. `libs/shared/assets`).
Thus, you can use pathing to any folder within the project (apps & libs) and will have nicely architectured new lib only for assets.

P.S. I can help on this issue if you want.

**Comment by trungk18** [comment]
@nikosanif Cheers! I think having a shared lib asset is a truly a best practice. Feel free to refactor the code and create a new PR. I'll be happy to review it. 

Notes: I am using lots of images for the repo README, please help to update there as well :)
