### ISSUE TITLE
No config for Spotify web app?

### ISSUE THREAD

**Issue by Jenni32222** [trungk18/angular-spotify#79]
Is this project using your Spotify application?

I would like to selfhost, whats the best approach using my own Spotify credentials?

**Comment by trungk18** [comment]
Hi, you could replace your `clientId` here.

https://github.com/trungk18/angular-spotify/blob/ec0403b74fac16a06980d40fdac60ce62290750d/libs/web/auth/data-access/src/lib/models/spotify-authorize.ts#L3

**Comment by trungk18** [comment]
Feel free to remove the google analytics as well. 

https://github.com/trungk18/angular-spotify/blob/main/apps/angular-spotify/src/app/google-analytics.service.ts
